### ISSUE TITLE
RuntimeError: Importer class <class 'peakrdl_ipxact.__peakrdl__.Importer'>

### ISSUE THREAD

**Issue by wgunawan** [SystemRDL/PeakRDL#22]
Hello,
 I just installed peakrdl by following instructions in https://peakrdl.readthedocs.io/en/latest/index.html
But when I try to run peakrdl (for example: peakrdl --help), it returns this error message:

File ".local/lib/python3.8/site-packages/peakrdl/plugins/importer.py", line 52, in get_importer_plugins
    raise RuntimeError(f"Importer class {cls} is expected to be extended from peakrdl.plugins.importer.ImporterPlugin")
RuntimeError: Importer class <class 'peakrdl_ipxact.__peakrdl__.Importer'> is expected to be extended from peakrdl.plugins.importer.ImporterPlugin

Did I miss something in my installation ?

Thank you.

**Comment by amykyta3** [comment]
Please make sure you are not pinning peakrdl-ipxact to an older version.
There was a recent plugin API change
