### ISSUE TITLE
SystemRDL community repository

### ISSUE THREAD

**Issue by Risto97** [SystemRDL/PeakRDL#23]
Hello,

Is there any plan to create a user repository for systemRDL peripherals (like the one for plugins), especially ones with peakrdl-regblock adapter?
I typically get myself "inspired" by commercial microcontrollers for some basic peripheral specifications. As I don't want to reinvent the wheel. 
I don't mind sharing some of them for others to use, maybe other people feel the same.

Of course, one needs to be careful how far we can get "inspired" until it gets into copyright issues. Any opinion on that?

**Comment by amykyta3** [comment]
I started this page that lists some community plugins to PeakRDL: https://github.com/SystemRDL/.github/blob/main/community_plugins.md

... but it sounds like you are referring to something else. Do you mean building a library of RDL files for existing devices? Or is this something else?

**Comment by Risto97** [comment]
No, I meant for the RDL files itself.
I know that it is not the scope of PeakRDL to provide RDL files as implementation.
But I feel like the format is highly reusable, and some basic peripherals openly available can help people to start using it and find reference on some good practices.

Currently its almost impossible to search through github for .rdl files, as its not an unique filetype extension.
Maybe making a curated list they would be more visible, and also possible to review the good and bad practices.
Also might encourage people to contribute

**Comment by amykyta3** [comment]
Sounds like a great idea.

**Comment by amykyta3** [comment]
Closing. If there is further discussion needed, feel free to re-open.
