### ISSUE TITLE
[FEATURE] PeakRDL Latex

### ISSUE THREAD

**Issue by Blebowski** [SystemRDL/PeakRDL#45]
**Is this related to a PeakRDL sub-command?**
No

**Describe the problem/limitation you think should be addressed**
Currently we use Latex as main language for most of our technical documentation. All our documentation templates
are built in a way to "plug-in" a Latex file with tables that describe register map of a single IP.

**Describe the solution you'd like**
We would like a new tool that would export directly LaTex output e.g. `peakrdl-latex`.

**Describe alternatives you've considered**
Using `peakrdl-markdown` and writing/using a converter from markdown to latex.
We are not fans of this solution since having this "local" out of mainline sources will
likely go out of date, and will remain maintained. We have ran into the pitfall of home-brew
register map toolchains way too many times to do this.

**Additional context**
We may be able to provide developers to work on this. @amykyta3 I have sent you LinkedIn invite
a while ago. Can we have a chat about peakRDL ?

**Comment by amykyta3** [comment]
That sounds like a great tool to add to the growing list of community plugins listed here: https://peakrdl.readthedocs.io/en/latest/community.html#community-plugins

Anyone can extend the tool with a PeakRDL plugin. For more details, see the [documentation on how to make a plugin](https://peakrdl.readthedocs.io/en/latest/for-devs/exporter-plugin.html).
