### ISSUE TITLE
Backdoor Support and Automated Sequence Generation in PeakRDL

### ISSUE THREAD

**Issue by umarcis** [SystemRDL/PeakRDL#46]
Hello **PeakRDL** Team,

As a **Design Verification Engineer**, I've been utilizing PeakRDL to generate automated RTL and Register Model (UVM) code, and I must say, it’s an excellent tool that significantly streamlines our workflow. However, I've identified a couple of features that could greatly enhance its functionality:

1. **Backdoor Support**: Implementing backdoor access in the generated UVM environment would provide a more efficient way to interact with internal signals, facilitating quicker and more effective verification processes.

2. **Automated Sequence Generation**: Introducing automated sequence generation would further reduce the manual effort involved in creating test sequences, allowing both verification and design engineers to focus on more complex tasks.

Integrating these features would not only enhance the usability of PeakRDL but also significantly reduce the cumbersome manual work that often accompanies the verification process.

I am failed to find these features, Could you people suggest something which is beneficial for my case.

Thanks,

Regards,
Umar

**Comment by amykyta3** [comment]
Backdoor support is something that will be implemented here: https://github.com/SystemRDL/PeakRDL-regblock/issues/15

As to automated sequence generation (beyond UVM's register tests), I'm afraid that is an extremely open-ended problem to solve. SystemRDL captures the register file structure, but not necessarily concrete information on the intent of its use.
If you have something specific in mind, I would recommend looking into making a community plugin, as PeakRDL is extensible. See: https://peakrdl.readthedocs.io/en/latest/for-devs/exporter-plugin.html
