### ISSUE TITLE
[FEATURE] Creation of automated CSR test for RISC-V, based on RDL register definition

### ISSUE THREAD

**Issue by chili-chips-ba** [SystemRDL/PeakRDL#49]
Given that PeakRDL already outputs UVM register views, which are typically used for automation of CSR test sequences, what it make sense to also automatically generate a 'C' program for execution of those test from an on-chip CPU?!

The same question is posed [here](https://github.com/chili-chips-ba/wireguard-fpga/issues/10#issue-2688219001), as our project is writing own post-processing script for adaptation of _PeakRDL_ register structures to our RISC-V ISS, as well as avoidance of expensive [Read-Modify-Write](https://github.com/chili-chips-ba/wireguard-fpga/issues/9#issuecomment-2496011101) sequences.

**Comment by amykyta3** [comment]
That sounds like a great tool to add to the growing list of community plugins listed here: https://peakrdl.readthedocs.io/en/latest/community.html#community-plugins

Anyone can extend the tool with a PeakRDL plugin. For more details, see the [documentation on how to make a plugin](https://peakrdl.readthedocs.io/en/latest/for-devs/exporter-plugin.html).
